# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  android: circleci/android@1.0.3
  gcp-cli: circleci/gcp-cli@2.2.0

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:

  unit-test: # A job to run unit test (Note: The name of the job can be anything you want it to be)
    executor:
      name: android/android-machine
      resource-class: large # Makes the build faster. For our free plan, large is what we are allowed to use else the build may fail.
    steps: # The steps block where we list the commands we want CircleCi to run when this job is called.
      - checkout # an inbuilt-pre-written command
      - android/restore-gradle-cache # an inbuilt-pre-written command
      - android/restore-build-cache # an inbuilt-pre-written command
      - android/run-tests: # an inbuilt-pre-written command
          test-command: ./gradlew testDebug # setting a parameter on this command
      - android/save-gradle-cache # an inbuilt-pre-written command
      - android/save-build-cache # an inbuilt-pre-written command
      - run: # a command that allows us write our own custom command. We are writing a custom command
          # to copy the unit tests results from the default path to a path were we want to display them.
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results: # an inbuilt-pre-written command
          path: ~/test-results
      - store_artifacts: # an inbuilt-pre-written command
          path: ~/test-results/junit

  release-build:
    executor:
      name: android/android-machine
      resource-class: large
    steps:
      - checkout
      - android/restore-gradle-cache
      - android/restore-build-cache
      - run:
          name: Assemble release build
          command: | # Here we are building the release variant using assembleRelease gradle instruction.
            ./gradlew assembleRelease
      - store_artifacts:
          path: app/build/outputs/apk/release/app-release-unsigned.apk

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - unit-test
      - release-build
